name: LLM Chatbot Augmented with Enterprise Data - V2
description: |
  This AMP demonstrates how to use an open source pre-trained instruction-following LLM (Large Language Model) to build a ChatBot-like web application. The responses of the LLM are enhanced by giving it context from an internal knowledge base. This context is retrieved by using an open source Vector Database to do semantic search.

author: Cloudera Inc.
specification_version: 1.0
prototype_version: 1.0
date: "2024-04-22"

runtimes:
  - editor: PBJ Workbench
    kernel: Python 3.10
    edition: Nvidia GPU

tasks:
  - type: run_session
    name: Install Dependencies
    script: 0_session-install-dependencies/install-dependencies.py
    short_summary: Install Dependencies
    kernel: python3
    cpu: 2
    memory: 8

  - type: run_session
    name: Download the models
    script: 0_session-install-dependencies/download_huggingface_model.py
    short_summary: Download the models from hugging face
    kernel: python3
    cpu: 2
    memory: 8

  - type: start_application
    name: CML LLM Chatbot - v2
    subdomain: cmlllmv2
    script: 3_app-run-python-script/front_end_app.py
    short_summary: Start CML LLM v2 Chatbot application
    long_summary: This application requires an available GPU to run the LLM model. Startup may be delayed if autoscaling is being performed or fail if GPU cannot be scheduled on this workspace. Please contact your administrator for GPU scheduling.
    cpu: 6
    memory: 24
    gpu: 0
    bypass_authentication: True
    environment_variables:
      TASK_TYPE: START_APPLICATION
      CML: yes
      TOKENIZERS_PARALLELISM: false